services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_NAME:-course_platform}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-course_platform}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: be
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_COLLECTOR_ADDR=jaeger:4317
      - REDIS_URL=redis:6379
    env_file:
      - be/.env
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully
      jaeger:
        condition: service_started
      redis:
        condition: service_started

  migrate:
    image: migrate/migrate
    volumes:
      - ./be/migrations:/migrations
    env_file:
      - be/.env
    command: -path=/migrations/ -database "postgres://${DB_USER:-postgres}:${DB_PASSWORD:-password}@db:5432/${DB_NAME:-course_platform}?sslmode=disable" up
    depends_on:
      db:
        condition: service_healthy

  fe:
    build:
      context: .
      dockerfile: fe/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://api:8080/api/v1
    depends_on:
      - api

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./be/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - api

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3001:3000" # Changed host port to 3001 to avoid conflict with Next.js
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686" # UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP

volumes:
  postgres_data:
