apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - hpa.yaml

images:
  - name: course-platform-api
    newName: your-registry/course-platform-api
    newTag: latest
